import type { Project } from '../../packages/resume/src/projects/types.ts';

export const GENERATED_FILE = new URL(
  '../../packages/resume/src/projects/generated/projects.ts',
  import.meta.url,
);

/**
 * `Project[]`를 결정적인 .ts 소스로 찍는다.
 *
 * 타임스탬프는 넣지 않는다 — 매 실행마다 diff가 생기면 `--check`가 무의미해진다.
 * biome은 이 디렉터리를 검사하지 않으므로(생성물 보호) 포맷은 JSON 그대로 둔다.
 */
export function emit(projects: Project[]): string {
  return [
    '// @generated by scripts/import-notion.ts — 직접 편집하지 말 것.',
    "import type { Project } from '../types';",
    '',
    `export const generatedProjects: Project[] = ${JSON.stringify(projects, null, 2)};`,
    '',
  ].join('\n');
}
